LOG_DIR_PATH = ''
PSWD_DIR_PATH =''
TMP_DIR_PATH=''

IMG_FILE_NAME = ''
LOG_FILE_NAME =''
ID_LIST_FILE_NAME =''

IMG_PATH = TMP_DIR_PATH + IMG_FILE_NAME
LOG_PATH = LOG_DIR_PATH + LOG_FILE_NAME
ID_LIST_PATH = PSWD_DIR_PATH + ID_LIST_FILE_NAME

CAMBOT_TOKEN = '' 
PSWD = ''
