CAMBOT_TOKEN = 'INSERT HERE THE TOKEN OF YOUR BOT' #Token del Bot
IMG_PATH = 'INSERT HERE THE PATH OF THE IMAGE GET FROM CAMERA'
LOG_PATH = 'INSERT HERE THE PATH OF THE LOG FILE'
PSWD = 'INSERT HERE THE PASSWORD'